name: Static Checks & Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.11"
      POETRY_VERSION: "1.7.1"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Run Style Checks
        run: |
          poetry run ruff format
      - name: Run Linting
        run: |
          poetry run ruff check
      - name: Run Type Checks
        run: |
          poetry run mypy smol/
      - name: Run Unit Tests
        run: |
          poetry run pytest
