name: Static Checks & Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry Dependencies
        run: |
          pip install -U pip poetry
          poetry install
      - name: Run Style Checks
        run: |
          poetry run black --check smol/
          poetry run black --check tests/
          poetry run black --check smol_cdk/
      - name: Run Linting
        run: |
          poetry run pylint smol/
          poetry run pylint smol_cdk/
      - name: Run Type Checks
        run: |
          poetry run mypy smol/
          poetry run mypy smol_cdk/
      - name: Run Dependency Check
        run: |
          poetry run safety check
      - name: Run Unit Tests
        run: |
          poetry run pytest
      - name: Report code coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
      - name: Setup Node for CDK
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install CDK Dependencies
        run: |
          npm install -g aws-cdk
      - name: Run CDK Check
        run: |
          poetry run cdk doctor
